baseurl = "/"
languageCode = "pt-br"
title = "Periódicos predatórios no QUALIS"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Início"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Metodologia"
    url = "/metodos/"
    weight = 2    
[[menu.main]]
    name = "Lista de predatórios"
    url = "/lista/"
    weight = 3
[[menu.main]]
    name = "Resumo Executivo"
    url = "/resumo/"
    weight = 4
[[menu.main]]
    name = "Resultados"
    url = "/resultados/"
    weight = 5
[params]
    description = "A website built through Hugo and blogdown."
    footer = "[Paulo Inácio Prado](http://ecologia.ib.usp.br/let/doku.php?id=engl:prado:start) &  [Roberto André Kraenkel](http://www.ift.unesp.br/users/kraenkel/) 2017 | [Github](https://github.com/piklprado/predatoryQUALIS) "
